name: cofeeshop
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.2.0
  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  provider: ^6.0.5
  badges: ^3.0.3
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.2
  intl: ^0.18.0
  flutter_slidable: ^2.0.0
  searchfield: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    

